services:
  db:
    image: postgres
    container_name: campusloc_db
    restart: always
    environment:
      POSTGRES_DB: campusloc
      POSTGRES_USER: eadarak
      POSTGRES_PASSWORD: eadarak
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
